services:
  - type: web
    name: telegram-bot
    env: python
    region: frankfurt
    plan: free
    buildCommand: ""
    startCommand: "python app_bot.py"
    envVars:
      - key: TOKEN
        sync: false
